#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""生成带 PrusaSlicer 风格缩略图的演示 gcode（纯标准库）。

用法: python3 make_sample_gcode.py <out_dir>
生成:
  demo_cube.gcode   —— 两个"零件"（演示 exclude_object），~100 层
  quick_line.gcode  —— 快速冒烟测试用小文件
"""
import base64
import math
import os
import struct
import sys
import zlib


def png_rgb(width, height, pixel_fn):
    """纯 python PNG 编码（RGB8）。pixel_fn(x,y)->(r,g,b)"""
    raw = bytearray()
    for y in range(height):
        raw.append(0)
        for x in range(width):
            r, g, b = pixel_fn(x, y)
            raw += bytes((r, g, b))
    def chunk(tag, data):
        c = struct.pack(">I", len(data)) + tag + data
        return c + struct.pack(">I", zlib.crc32(tag + data) & 0xFFFFFFFF)
    ihdr = struct.pack(">IIBBBBB", width, height, 8, 2, 0, 0, 0)
    return (b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", ihdr)
            + chunk(b"IDAT", zlib.compress(bytes(raw), 6))
            + chunk(b"IEND", b""))


def make_thumb(size):
    """画一个渐变色背景 + 立方体线框风格的简单图案"""
    def px(x, y):
        # 背景渐变（深蓝->紫）
        t = y / max(1, size - 1)
        r = int(30 + 90 * t)
        g = int(40 + 30 * t)
        b = int(90 + 90 * t)
        # 中央画一个"立方体"
        cx, cy = size / 2, size / 2
        L = size * 0.30
        # 顶面菱形
        dx, dy = abs(x - cx), abs(y - (cy - L * 0.45))
        if dx + dy * 2 < L:
            r, g, b = 240, 180, 60
        # 左面
        if cy - L * 0.45 < y < cy + L * 0.75 and \
                abs(x - (cx - L * 0.55)) < L * 0.5 and x < cx:
            r, g, b = 200, 120, 40
        # 右面
        if cy - L * 0.45 < y < cy + L * 0.75 and \
                abs(x - (cx + L * 0.55)) < L * 0.5 and x >= cx:
            r, g, b = 160, 90, 35
        return r, g, b
    return png_rgb(size, size, px)


def thumbnail_block(png_bytes, size):
    b64 = base64.b64encode(png_bytes).decode()
    # 头部声明的长度是 base64 字符数（Moonraker 按此校验），不是 PNG 字节数
    lines = ["; thumbnail begin %dx%d %d" % (size, size, len(b64))]
    for i in range(0, len(b64), 78):
        lines.append("; " + b64[i:i + 78])
    lines.append("; thumbnail end")
    return "\n".join(lines) + "\n"


def gen_cube_file(path):
    layers = 120
    layer_h = 0.2
    size = 40.0          # 零件边长 mm
    cx1, cy1 = 85.0, 100.0   # part1 中心
    cx2, cy2 = 155.0, 100.0  # part2 中心
    perim_segments = 8       # 每边分段
    feed = 1800              # mm/min
    e_per_mm = 0.033
    filament_total = 0.0

    out = []
    out.append("; generated by PrusaSlicer 2.9.2 on 2026-10-05 at 12:00:00 UTC")
    out.append(";LAYER_COUNT:%d" % layers)
    out.append("; filament used [mm] = 2500.0")
    for sz in (32, 64, 300):
        out.append(thumbnail_block(make_thumb(sz), sz).rstrip("\n"))
    out.append('EXCLUDE_OBJECT_DEFINE NAME=part1 CENTER=[%s,%s] '
               'POLYGON=[[%s,%s],[%s,%s],[%s,%s],[%s,%s]]'
               % (cx1, cy1, cx1 - size / 2, cy1 - size / 2,
                  cx1 + size / 2, cy1 - size / 2,
                  cx1 + size / 2, cy1 + size / 2,
                  cx1 - size / 2, cy1 + size / 2))
    out.append('EXCLUDE_OBJECT_DEFINE NAME=part2 CENTER=[%s,%s] '
               'POLYGON=[[%s,%s],[%s,%s],[%s,%s],[%s,%s]]'
               % (cx2, cy2, cx2 - size / 2, cy2 - size / 2,
                  cx2 + size / 2, cy2 - size / 2,
                  cx2 + size / 2, cy2 + size / 2,
                  cx2 - size / 2, cy2 + size / 2))
    out.append("START_PRINT BED=60 EXTRUDER=205")
    out.append("SET_PRINT_STATS_INFO TOTAL_LAYER=%d" % layers)
    out.append("M83")  # 相对挤出
    e = 0.0
    for layer in range(layers):
        z = round(0.3 + layer * layer_h, 3)
        out.append(";LAYER:%d" % layer)
        out.append("M73 P%d" % int((layer + 1) * 100 / layers))
        out.append("G1 Z%.3f F600" % z)
        for name, cx, cy in (("part1", cx1, cy1), ("part2", cx2, cy2)):
            out.append("EXCLUDE_OBJECT NAME=%s" % "part1"
                       if False else "EXCLUDE_OBJECT CURRENT=%s" % name)
            half = size / 2
            out.append("G1 X%.3f Y%.3f F9000" % (cx - half, cy - half))
            n = perim_segments
            for side in range(4):
                for s in range(1, n + 1):
                    f = s / n
                    if side == 0:
                        x, y = cx - half + size * f, cy - half
                    elif side == 1:
                        x, y = cx + half, cy - half + size * f
                    elif side == 2:
                        x, y = cx + half - size * f, cy + half
                    else:
                        x, y = cx - half, cy + half - size * f
                    out.append("G1 X%.3f Y%.3f E%.4f F%d"
                               % (x, y, size / n * e_per_mm, feed))
                    filament_total += size / n * e_per_mm
    out.append("END_PRINT")
    # PrusaSlicer 风格的配置尾注（Moonraker 元数据解析从这里取层高/耗时等）
    out += ["",
            "; prusaslicer_config = begin",
            "; layer_height = 0.2",
            "; first_layer_height = 0.3",
            "; nozzle_diameter = 0.4",
            "; filament_type = PLA",
            "; filament used [mm] = 2500.0",
            "; total filament used [g] = 7.4",
            "; estimated printing time (normal mode) = 1h 5m 24s",
            "; first_layer_temperature = 210",
            "; bed_temperature = 60",
            "; prusaslicer_config = end"]
    data = "\n".join(out) + "\n"
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(data)
    return len(data)


def gen_quick_file(path):
    # 层数要让 16KB/s 的字节回放撑满几秒，给暂停/恢复/取消留出操作窗口
    layers = 600
    out = ["; generated by PrusaSlicer 2.9.2 on 2026-10-05 at 12:00:00 UTC",
           "; quick smoke-test print",
           ";LAYER_COUNT:%d" % layers,
           "; filament used [mm] = 120.0",
           thumbnail_block(make_thumb(32), 32).rstrip("\n"),
           thumbnail_block(make_thumb(64), 64).rstrip("\n"),
           "START_PRINT BED=50 EXTRUDER=195",
           "SET_PRINT_STATS_INFO TOTAL_LAYER=%d" % layers,
           "M83"]
    for layer in range(layers):
        out.append(";LAYER:%d" % layer)
        out.append("M73 P%d" % int((layer + 1) * 100 / layers))
        out.append("G1 Z%.2f F600" % (0.3 + layer * 0.2))
        out.append("G1 X60 Y100 E1.2 F1800")
        out.append("G1 X180 Y100 E1.2 F1800")
        out.append("G1 X180 Y140 E0.4 F1800")
        out.append("G1 X60 Y140 E1.2 F1800")
        out.append("G1 X60 Y100 E0.4 F1800")
    out.append("END_PRINT")
    data = "\n".join(out) + "\n"
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(data)
    return len(data)


def main():
    out_dir = sys.argv[1]
    os.makedirs(out_dir, exist_ok=True)
    for name, fn in (("demo_cube.gcode", gen_cube_file),
                     ("quick_line.gcode", gen_quick_file)):
        p = os.path.join(out_dir, name)
        n = fn(p)
        print("%s: %d bytes" % (p, n))


if __name__ == "__main__":
    main()
